"""empty message

Revision ID: 030f266965e1
Revises: 6d944a1397bd
Create Date: 2019-11-08 20:48:33.424049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '030f266965e1'
down_revision = '6d944a1397bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('Course_type', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('course', 'course_type')
    # ### end Alembic commands ###
