"""empty message

Revision ID: 2c796b9fda64
Revises: 030f266965e1
Create Date: 2019-11-09 11:14:47.739599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c796b9fda64'
down_revision = '030f266965e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_ibfk_1', 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'course', ['course_code'], ['code'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key('classes_ibfk_1', 'classes', 'course', ['course_code'], ['code'])
    # ### end Alembic commands ###
