"""empty message

Revision ID: 33419dbd182c
Revises: 3568b9e320b0
Create Date: 2019-11-09 16:29:20.496888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33419dbd182c'
down_revision = '3568b9e320b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_ibfk_3', 'classes', type_='foreignkey')
    op.drop_column('classes', 'course_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('course_code', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('classes_ibfk_3', 'classes', 'course', ['course_code'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###
