"""empty message

Revision ID: 3568b9e320b0
Revises: 2c796b9fda64
Create Date: 2019-11-09 12:49:30.171885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3568b9e320b0'
down_revision = '2c796b9fda64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_ibfk_2', 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'faculty', ['faculty_id'], ['id'], onupdate='cascade')
    op.drop_constraint('ia_1_ibfk_1', 'ia_1', type_='foreignkey')
    op.create_foreign_key(None, 'ia_1', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_constraint('ia_2_ibfk_1', 'ia_2', type_='foreignkey')
    op.create_foreign_key(None, 'ia_2', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_constraint('ia_3_ibfk_1', 'ia_3', type_='foreignkey')
    op.create_foreign_key(None, 'ia_3', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'classes', ['class_id'], ['id'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'classes', ['class_id'], ['id'])
    op.drop_constraint(None, 'ia_3', type_='foreignkey')
    op.create_foreign_key('ia_3_ibfk_1', 'ia_3', 'student', ['usn'], ['usn'])
    op.drop_constraint(None, 'ia_2', type_='foreignkey')
    op.create_foreign_key('ia_2_ibfk_1', 'ia_2', 'student', ['usn'], ['usn'])
    op.drop_constraint(None, 'ia_1', type_='foreignkey')
    op.create_foreign_key('ia_1_ibfk_1', 'ia_1', 'student', ['usn'], ['usn'])
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key('classes_ibfk_2', 'classes', 'faculty', ['faculty_id'], ['id'])
    # ### end Alembic commands ###
