"""empty message

Revision ID: 3c039d3d9ad7
Revises: 
Create Date: 2019-11-08 00:14:55.834032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c039d3d9ad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_email'), 'faculty', ['email'], unique=True)
    op.create_index(op.f('ix_faculty_first_name'), 'faculty', ['first_name'], unique=False)
    op.create_index(op.f('ix_faculty_last_name'), 'faculty', ['last_name'], unique=False)
    op.create_table('course',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('Course_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('classes',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.code'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('usn', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_last_name'), 'student', ['last_name'], unique=False)
    op.create_index(op.f('ix_student_usn'), 'student', ['usn'], unique=False)
    op.create_table('ia_1',
    sa.Column('usn', sa.String(length=10), nullable=False),
    sa.Column('cs51', sa.Integer(), nullable=True),
    sa.Column('cs52', sa.Integer(), nullable=True),
    sa.Column('cs53', sa.Integer(), nullable=True),
    sa.Column('cs54', sa.Integer(), nullable=True),
    sa.Column('cs553', sa.Integer(), nullable=True),
    sa.Column('cs562', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    op.create_table('ia_2',
    sa.Column('usn', sa.String(length=10), nullable=False),
    sa.Column('cs51', sa.Integer(), nullable=True),
    sa.Column('cs52', sa.Integer(), nullable=True),
    sa.Column('cs53', sa.Integer(), nullable=True),
    sa.Column('cs54', sa.Integer(), nullable=True),
    sa.Column('cs553', sa.Integer(), nullable=True),
    sa.Column('cs562', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    op.create_table('ia_3',
    sa.Column('usn', sa.String(length=10), nullable=False),
    sa.Column('cs51', sa.Integer(), nullable=True),
    sa.Column('cs52', sa.Integer(), nullable=True),
    sa.Column('cs53', sa.Integer(), nullable=True),
    sa.Column('cs54', sa.Integer(), nullable=True),
    sa.Column('cs553', sa.Integer(), nullable=True),
    sa.Column('cs562', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usn'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('usn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ia_3')
    op.drop_table('ia_2')
    op.drop_table('ia_1')
    op.drop_index(op.f('ix_student_usn'), table_name='student')
    op.drop_index(op.f('ix_student_last_name'), table_name='student')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    op.drop_table('classes')
    op.drop_table('course')
    op.drop_index(op.f('ix_faculty_last_name'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_first_name'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_email'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
