"""empty message

Revision ID: 6d944a1397bd
Revises: 253ca68af837
Create Date: 2019-11-08 20:04:24.682126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d944a1397bd'
down_revision = '253ca68af837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('scheme', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'scheme')
    # ### end Alembic commands ###
