"""empty message

Revision ID: 9710882185b1
Revises: 97df4e4d9876
Create Date: 2019-11-14 21:31:27.133507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9710882185b1'
down_revision = '97df4e4d9876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'id')
    # ### end Alembic commands ###
