"""empty message

Revision ID: 97df4e4d9876
Revises: 65d13c01da88
Create Date: 2019-11-10 10:56:55.454168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97df4e4d9876'
down_revision = '65d13c01da88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('is_classteacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'is_classteacher')
    # ### end Alembic commands ###
