"""empty message

Revision ID: acdd93bf3411
Revises: 1fac1a33d279
Create Date: 2019-11-18 14:38:57.324431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acdd93bf3411'
down_revision = '1fac1a33d279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ia_1_ibfk_1', 'ia_1', type_='foreignkey')
    op.create_foreign_key(None, 'ia_1', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_constraint('ia_2_ibfk_1', 'ia_2', type_='foreignkey')
    op.create_foreign_key(None, 'ia_2', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_constraint('ia_3_ibfk_1', 'ia_3', type_='foreignkey')
    op.create_foreign_key(None, 'ia_3', 'student', ['usn'], ['usn'], onupdate='cascade')
    op.drop_column('student', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'ia_3', type_='foreignkey')
    op.create_foreign_key('ia_3_ibfk_1', 'ia_3', 'student', ['usn'], ['usn'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'ia_2', type_='foreignkey')
    op.create_foreign_key('ia_2_ibfk_1', 'ia_2', 'student', ['usn'], ['usn'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'ia_1', type_='foreignkey')
    op.create_foreign_key('ia_1_ibfk_1', 'ia_1', 'student', ['usn'], ['usn'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
