"""empty message

Revision ID: d488178a75a3
Revises: 0f926e0bd565
Create Date: 2019-11-08 18:49:31.116641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd488178a75a3'
down_revision = '0f926e0bd565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'semester')
    # ### end Alembic commands ###
